spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:lunch_voting
    # tcp: jdbc:h2:tcp://localhost:9092/mem:diploma
    # Absolute path
    #    url: jdbc:h2:C:/projects/diploma/db/diploma
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/diploma/db/diploma
    # Relative path form current dir
    #    url: jdbc:h2:./db/diploma
    # Relative path from home
    #    url: jdbc:h2:~/diploma
    #    tcp: jdbc:h2:tcp://localhost:9092/~/diploma
    username: sa
    password:

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  cache:
    cache-names: foods, restaurants
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

springdoc.swagger-ui.path: /
