spring:
  #  profiles.active: dev

  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    properties.hibernate:
      format_sql: true
      default_batch_fetch_size: 20
      jdbc.batch_size: 20

  sql.init.mode: always

  datasource:
    url: jdbc:h2:mem:lunch_voting
    username: sa
    password:
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

server.error.include-message: always

# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
#  cache:
#    cache-names: restWithMenu,menus,restaurants
#    caffeine.spec: maximumSize=1000,expireAfterAccess=600s

server.servlet.encoding:
  charset: UTF-8
  enabled: true
  force: true

#springdoc:
#  swagger-ui:
#    tagsSorter: alpha
#    operationsSorter: alpha

#voting:
#  voteEnding: "11:00"